feat(flatpak-builder): Allow configurable build/repo/state dirs (#237)
* feat(flatpak-builder): Allow configurable build/repo/state dirs

Previously, the flatpak-builder action used hardcoded directories for the build output, local repository, and build state. This change introduces new input parameters to make these directories configurable:

-   'build-dir': Specifies the directory for the application build output.
-   'repo-name': Specifies the directory for the flatpak repository.
-   'state-dir': Specifies the directory to store the build cache.

This flexibility is crucial for environments like GitHub Actions, where default working directories might have limited space. By allowing users to specify paths, they can leverage volume mountpoints (e.g., /mnt) that offer more disk space, preventing "running out of space" errors during the build process.

Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

* feat(ci): Add flatpak-builder dedicated path params test job

Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

* refactor: Rename repo-name to repo-dir for clarity

Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

* ci: Add verification for created flatpak directories

Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

* ci: update flatpak-builder action repo-dir parameter

Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

---------

Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

diff --git a/.github/workflows/flatpak-test.yml b/.github/workflows/flatpak-test.yml
--- a/.github/workflows/flatpak-test.yml
+++ b/.github/workflows/flatpak-test.yml
@@ -86,6 +86,34 @@ jobs:
           cache-key: flatpak-builder-${{ github.sha }}-no-cache-restored
           verbose: true
 
+  flatpak-builder-dedicated-path-params:
+    name: Flatpak Builder with Dedicated Path Params
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
+      options: --privileged
+      volumes:
+        - /mnt/flatpak_workflow:/mnt/flatpak_workflow
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./flatpak-builder
+        with:
+          manifest-path: ./flatpak-builder/tests/test-project/org.example.MyApp.yaml
+          build-dir: /mnt/flatpak_workflow/build-dir
+          repo-dir: /mnt/flatpak_workflow/repo
+          state-dir: /mnt/flatpak_workflow/.flatpak-builder
+          verbose: true
+      - name: Verify created directories
+        shell: bash
+        run: |
+          for d in \
+            /mnt/flatpak_workflow/build-dir \
+            /mnt/flatpak_workflow/repo \
+            /mnt/flatpak_workflow/.flatpak-builder
+          do
+            [ -d "$d" ] || { echo "::error::Directory $d does not exist"; exit 1; }
+          done
+
   tests:
     name: Tests
     runs-on: ubuntu-latest
